/////////////////////////////////
// SELECTING QUERIES
const btnNewGrid = document.querySelector('.btn-new-grid');
const gridContainer = document.querySelector('.container');
let tiles;
const mainHeader = document.querySelector('.main-header');
const instructions = document.querySelector('.instructions');
const userGridGenerator = document.querySelector('.user-grid-generator');
const intro = document.querySelector('.intro');
const userGridInstructions = document.querySelector('.user-grid-instructions');
const btnUserGrid = document.querySelector('.btn-user-grid');
const userTileNumber = document.querySelector('.user-tile-input');
let drawingMode = false;

/////////////////////////////////
// GENERATING INITAL GRID
let gridSize = 16;
let tileWidth = `${60/gridSize}rem`;
let tileHeight = `${60/gridSize}rem`;


btnNewGrid.addEventListener('click', function(){
    createGrid();

    tiles = document.querySelectorAll('.tile');

    intro.classList.add('hidden');
    instructions.classList.remove('hidden');
    userGridInstructions.classList.remove('hidden');
    
    gridContainer.classList.remove('hidden');
    btnNewGrid.classList.add('hidden');
    userGridGenerator.classList.remove('hidden');

//    drawingOnOff();

});

function createGrid() {
    tileWidth = `${60/gridSize}rem`;
    let tileHeight = `${60/gridSize}rem`;

    for (let i=1; i <= (gridSize*gridSize); i++) {
        const div = document.createElement('div');
    div.className = 'tile';
    div.style.width = tileWidth;
    div.style.height = tileHeight;
    gridContainer.appendChild(div);
    };

    tiles = document.querySelectorAll('.tile');
};

/////////////////////////////////
// GRID GENERATED BY THE USER 

function removeCurrentGrid() {
    tiles.forEach((tile)=>tile.remove());
}

btnUserGrid.addEventListener('click',function(){
    if(parseInt(userTileNumber.value)<=100) {
        gridSize = parseInt(userTileNumber.value);
        removeCurrentGrid();
        createGrid();
        // drawingOnOff();
    } else {
        console.log("whoa whoa whoa!")
    };
});

/////////////////////////////////
// GRID MOUSE EVENTS

gridContainer.addEventListener('click', function(){
    activateDrawing();

    if(!drawingMode) drawingMode = true;
    else if(drawingMode) drawingMode = false;
});

function activateDrawing() {
    tiles.forEach((tile) => {
        tile.addEventListener('mouseover', function(){
            if(drawingMode) tile.style.backgroundColor = "grey";
            else if(!drawingMode) return;
        });
    });

    console.log(`Your drawing mode is now ${drawingMode}`)
    return;
};








